name: Deploy to ECS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Create ECS Cluster
      env:
        AWS_REGION: us-east-1
      run: |
        aws ecs create-cluster --cluster-name my-ecs-cluster --region $AWS_REGION || echo "Cluster already exists"

    - name: Deploy to ECS
      env:
        AWS_DEFAULT_REGION: us-east-1
        ECS_CLUSTER: my-ecs-cluster
        ECS_SERVICE: smallCat
        IMAGE_URI: 065334477167.dkr.ecr.us-east-1.amazonaws.com/my-smallapp:latest
      run: |
        - echo 1
        - TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition "smallCat" --region "$AWS_DEFAULT_REGION")
        - echo 2
        - NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "$IMAGE_URI" '.taskDefinition | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) |  del(.registeredAt)  | del(.registeredBy)')
        - echo 3
        - NEW_TASK_INFO=$(aws ecs register-task-definition --region "$AWS_DEFAULT_REGION" --cli-input-json "$NEW_TASK_DEFINITION")
        - echo 4
        - NEW_REVISION=$(echo $NEW_TASK_INFO | jq '.taskDefinition.revision')
        - echo 5
        - aws ecs update-service --cluster ${ECS_CLUSTER} --service ${ECS_SERVICE} --task-definition smallCat:${NEW_REVISION}
